# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1364, 1028)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.glasses1transparent = QtWidgets.QLabel(self.centralwidget)
        self.glasses1transparent.setGeometry(QtCore.QRect(140, 80, 120, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses1transparent.sizePolicy().hasHeightForWidth())
        self.glasses1transparent.setSizePolicy(sizePolicy)
        self.glasses1transparent.setMaximumSize(QtCore.QSize(120, 120))
        self.glasses1transparent.setAutoFillBackground(False)
        self.glasses1transparent.setText("")
        self.glasses1transparent.setPixmap(QtGui.QPixmap("images/ghost90.png"))
        self.glasses1transparent.setScaledContents(True)
        self.glasses1transparent.setObjectName("glasses1transparent")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, -50, 1511, 1171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background.sizePolicy().hasHeightForWidth())
        self.background.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.background.setFont(font)
        self.background.setAutoFillBackground(False)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("images/gui1background.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.element2 = QtWidgets.QLabel(self.centralwidget)
        self.element2.setGeometry(QtCore.QRect(11, 78, 731, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2.sizePolicy().hasHeightForWidth())
        self.element2.setSizePolicy(sizePolicy)
        self.element2.setAutoFillBackground(False)
        self.element2.setFrameShape(QtWidgets.QFrame.Box)
        self.element2.setText("")
        self.element2.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2.setScaledContents(True)
        self.element2.setObjectName("element2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 102, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.element3_2 = QtWidgets.QLabel(self.centralwidget)
        self.element3_2.setGeometry(QtCore.QRect(1010, 20, 231, 811))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element3_2.sizePolicy().hasHeightForWidth())
        self.element3_2.setSizePolicy(sizePolicy)
        self.element3_2.setAutoFillBackground(False)
        self.element3_2.setFrameShape(QtWidgets.QFrame.Box)
        self.element3_2.setText("")
        self.element3_2.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element3_2.setScaledContents(True)
        self.element3_2.setObjectName("element3_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(141, 88, 601, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.glasses2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses2.sizePolicy().hasHeightForWidth())
        self.glasses2.setSizePolicy(sizePolicy)
        self.glasses2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses2.setText("")
        self.glasses2.setPixmap(QtGui.QPixmap("images/glassesempty.png"))
        self.glasses2.setScaledContents(True)
        self.glasses2.setObjectName("glasses2")
        self.horizontalLayout.addWidget(self.glasses2)
        self.glasses5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses5.sizePolicy().hasHeightForWidth())
        self.glasses5.setSizePolicy(sizePolicy)
        self.glasses5.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses5.setText("")
        self.glasses5.setPixmap(QtGui.QPixmap("images/glassesclear.png"))
        self.glasses5.setScaledContents(True)
        self.glasses5.setObjectName("glasses5")
        self.horizontalLayout.addWidget(self.glasses5)
        self.glasses3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses3.sizePolicy().hasHeightForWidth())
        self.glasses3.setSizePolicy(sizePolicy)
        self.glasses3.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses3.setText("")
        self.glasses3.setPixmap(QtGui.QPixmap("images/glassesyellow.png"))
        self.glasses3.setScaledContents(True)
        self.glasses3.setObjectName("glasses3")
        self.horizontalLayout.addWidget(self.glasses3)
        self.glasses4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses4.sizePolicy().hasHeightForWidth())
        self.glasses4.setSizePolicy(sizePolicy)
        self.glasses4.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses4.setText("")
        self.glasses4.setPixmap(QtGui.QPixmap("images/glassesblue.png"))
        self.glasses4.setScaledContents(True)
        self.glasses4.setObjectName("glasses4")
        self.horizontalLayout.addWidget(self.glasses4)
        self.glasses1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses1.sizePolicy().hasHeightForWidth())
        self.glasses1.setSizePolicy(sizePolicy)
        self.glasses1.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses1.setText("")
        self.glasses1.setPixmap(QtGui.QPixmap("images/glassesred.png"))
        self.glasses1.setScaledContents(True)
        self.glasses1.setObjectName("glasses1")
        self.horizontalLayout.addWidget(self.glasses1)
        self.glasses2transparent = QtWidgets.QLabel(self.centralwidget)
        self.glasses2transparent.setGeometry(QtCore.QRect(260, 80, 120, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses2transparent.sizePolicy().hasHeightForWidth())
        self.glasses2transparent.setSizePolicy(sizePolicy)
        self.glasses2transparent.setMaximumSize(QtCore.QSize(120, 120))
        self.glasses2transparent.setAutoFillBackground(False)
        self.glasses2transparent.setText("")
        self.glasses2transparent.setPixmap(QtGui.QPixmap("images/ghost90.png"))
        self.glasses2transparent.setScaledContents(True)
        self.glasses2transparent.setObjectName("glasses2transparent")
        self.glasses5transparent = QtWidgets.QLabel(self.centralwidget)
        self.glasses5transparent.setEnabled(True)
        self.glasses5transparent.setGeometry(QtCore.QRect(620, 80, 120, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses5transparent.sizePolicy().hasHeightForWidth())
        self.glasses5transparent.setSizePolicy(sizePolicy)
        self.glasses5transparent.setMaximumSize(QtCore.QSize(120, 120))
        self.glasses5transparent.setAutoFillBackground(False)
        self.glasses5transparent.setText("")
        self.glasses5transparent.setPixmap(QtGui.QPixmap("images/ghost90.png"))
        self.glasses5transparent.setScaledContents(True)
        self.glasses5transparent.setObjectName("glasses5transparent")
        self.element2_2 = QtWidgets.QLabel(self.centralwidget)
        self.element2_2.setGeometry(QtCore.QRect(10, 760, 201, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_2.sizePolicy().hasHeightForWidth())
        self.element2_2.setSizePolicy(sizePolicy)
        self.element2_2.setAutoFillBackground(False)
        self.element2_2.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.element2_2.setText("")
        self.element2_2.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_2.setScaledContents(True)
        self.element2_2.setObjectName("element2_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 760, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1020, 30, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.glasses3transparent = QtWidgets.QLabel(self.centralwidget)
        self.glasses3transparent.setGeometry(QtCore.QRect(380, 80, 120, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses3transparent.sizePolicy().hasHeightForWidth())
        self.glasses3transparent.setSizePolicy(sizePolicy)
        self.glasses3transparent.setMaximumSize(QtCore.QSize(120, 120))
        self.glasses3transparent.setAutoFillBackground(False)
        self.glasses3transparent.setText("")
        self.glasses3transparent.setPixmap(QtGui.QPixmap("images/ghost90.png"))
        self.glasses3transparent.setScaledContents(True)
        self.glasses3transparent.setObjectName("glasses3transparent")
        self.glasses4transparent = QtWidgets.QLabel(self.centralwidget)
        self.glasses4transparent.setGeometry(QtCore.QRect(500, 80, 120, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses4transparent.sizePolicy().hasHeightForWidth())
        self.glasses4transparent.setSizePolicy(sizePolicy)
        self.glasses4transparent.setMaximumSize(QtCore.QSize(120, 120))
        self.glasses4transparent.setAutoFillBackground(False)
        self.glasses4transparent.setText("")
        self.glasses4transparent.setPixmap(QtGui.QPixmap("images/ghost90.png"))
        self.glasses4transparent.setScaledContents(True)
        self.glasses4transparent.setObjectName("glasses4transparent")
        self.warning = QtWidgets.QLabel(self.centralwidget)
        self.warning.setGeometry(QtCore.QRect(430, 240, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning.sizePolicy().hasHeightForWidth())
        self.warning.setSizePolicy(sizePolicy)
        self.warning.setMinimumSize(QtCore.QSize(500, 500))
        self.warning.setMaximumSize(QtCore.QSize(500, 500))
        self.warning.setText("")
        self.warning.setPixmap(QtGui.QPixmap("images/exclamation.png"))
        self.warning.setScaledContents(True)
        self.warning.setObjectName("warning")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 345, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.element3_3 = QtWidgets.QLabel(self.centralwidget)
        self.element3_3.setGeometry(QtCore.QRect(10, 340, 731, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element3_3.sizePolicy().hasHeightForWidth())
        self.element3_3.setSizePolicy(sizePolicy)
        self.element3_3.setAutoFillBackground(False)
        self.element3_3.setFrameShape(QtWidgets.QFrame.Box)
        self.element3_3.setText("")
        self.element3_3.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element3_3.setScaledContents(True)
        self.element3_3.setObjectName("element3_3")
        self.glasses5transparent2 = QtWidgets.QLabel(self.centralwidget)
        self.glasses5transparent2.setEnabled(True)
        self.glasses5transparent2.setGeometry(QtCore.QRect(620, 210, 120, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses5transparent2.sizePolicy().hasHeightForWidth())
        self.glasses5transparent2.setSizePolicy(sizePolicy)
        self.glasses5transparent2.setMaximumSize(QtCore.QSize(120, 120))
        self.glasses5transparent2.setAutoFillBackground(False)
        self.glasses5transparent2.setText("")
        self.glasses5transparent2.setPixmap(QtGui.QPixmap("images/ghost90.png"))
        self.glasses5transparent2.setScaledContents(True)
        self.glasses5transparent2.setObjectName("glasses5transparent2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 230, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(24)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(140, 216, 601, 102))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.glasses2_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses2_2.sizePolicy().hasHeightForWidth())
        self.glasses2_2.setSizePolicy(sizePolicy)
        self.glasses2_2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses2_2.setText("")
        self.glasses2_2.setPixmap(QtGui.QPixmap("images/glassesempty.png"))
        self.glasses2_2.setScaledContents(True)
        self.glasses2_2.setObjectName("glasses2_2")
        self.horizontalLayout_2.addWidget(self.glasses2_2)
        self.glasses5_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses5_2.sizePolicy().hasHeightForWidth())
        self.glasses5_2.setSizePolicy(sizePolicy)
        self.glasses5_2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses5_2.setText("")
        self.glasses5_2.setPixmap(QtGui.QPixmap("images/glassesclear.png"))
        self.glasses5_2.setScaledContents(True)
        self.glasses5_2.setObjectName("glasses5_2")
        self.horizontalLayout_2.addWidget(self.glasses5_2)
        self.glasses3_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses3_2.sizePolicy().hasHeightForWidth())
        self.glasses3_2.setSizePolicy(sizePolicy)
        self.glasses3_2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses3_2.setText("")
        self.glasses3_2.setPixmap(QtGui.QPixmap("images/glassesyellow.png"))
        self.glasses3_2.setScaledContents(True)
        self.glasses3_2.setObjectName("glasses3_2")
        self.horizontalLayout_2.addWidget(self.glasses3_2)
        self.glasses4_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses4_2.sizePolicy().hasHeightForWidth())
        self.glasses4_2.setSizePolicy(sizePolicy)
        self.glasses4_2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses4_2.setText("")
        self.glasses4_2.setPixmap(QtGui.QPixmap("images/glassesblue.png"))
        self.glasses4_2.setScaledContents(True)
        self.glasses4_2.setObjectName("glasses4_2")
        self.horizontalLayout_2.addWidget(self.glasses4_2)
        self.glasses1_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses1_2.sizePolicy().hasHeightForWidth())
        self.glasses1_2.setSizePolicy(sizePolicy)
        self.glasses1_2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses1_2.setText("")
        self.glasses1_2.setPixmap(QtGui.QPixmap("images/glassesred.png"))
        self.glasses1_2.setScaledContents(True)
        self.glasses1_2.setObjectName("glasses1_2")
        self.horizontalLayout_2.addWidget(self.glasses1_2)
        self.glasses4transparent2 = QtWidgets.QLabel(self.centralwidget)
        self.glasses4transparent2.setGeometry(QtCore.QRect(500, 210, 120, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses4transparent2.sizePolicy().hasHeightForWidth())
        self.glasses4transparent2.setSizePolicy(sizePolicy)
        self.glasses4transparent2.setMaximumSize(QtCore.QSize(120, 120))
        self.glasses4transparent2.setAutoFillBackground(False)
        self.glasses4transparent2.setText("")
        self.glasses4transparent2.setPixmap(QtGui.QPixmap("images/ghost90.png"))
        self.glasses4transparent2.setScaledContents(True)
        self.glasses4transparent2.setObjectName("glasses4transparent2")
        self.glasses2transparent2 = QtWidgets.QLabel(self.centralwidget)
        self.glasses2transparent2.setGeometry(QtCore.QRect(260, 210, 120, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses2transparent2.sizePolicy().hasHeightForWidth())
        self.glasses2transparent2.setSizePolicy(sizePolicy)
        self.glasses2transparent2.setMaximumSize(QtCore.QSize(120, 120))
        self.glasses2transparent2.setAutoFillBackground(False)
        self.glasses2transparent2.setText("")
        self.glasses2transparent2.setPixmap(QtGui.QPixmap("images/ghost90.png"))
        self.glasses2transparent2.setScaledContents(True)
        self.glasses2transparent2.setObjectName("glasses2transparent2")
        self.element2_3 = QtWidgets.QLabel(self.centralwidget)
        self.element2_3.setGeometry(QtCore.QRect(10, 206, 731, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_3.sizePolicy().hasHeightForWidth())
        self.element2_3.setSizePolicy(sizePolicy)
        self.element2_3.setAutoFillBackground(False)
        self.element2_3.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_3.setText("")
        self.element2_3.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_3.setScaledContents(True)
        self.element2_3.setObjectName("element2_3")
        self.glasses3transparent2 = QtWidgets.QLabel(self.centralwidget)
        self.glasses3transparent2.setGeometry(QtCore.QRect(380, 210, 120, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses3transparent2.sizePolicy().hasHeightForWidth())
        self.glasses3transparent2.setSizePolicy(sizePolicy)
        self.glasses3transparent2.setMaximumSize(QtCore.QSize(120, 120))
        self.glasses3transparent2.setAutoFillBackground(False)
        self.glasses3transparent2.setText("")
        self.glasses3transparent2.setPixmap(QtGui.QPixmap("images/ghost90.png"))
        self.glasses3transparent2.setScaledContents(True)
        self.glasses3transparent2.setObjectName("glasses3transparent2")
        self.glasses1transparent2 = QtWidgets.QLabel(self.centralwidget)
        self.glasses1transparent2.setGeometry(QtCore.QRect(140, 210, 120, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses1transparent2.sizePolicy().hasHeightForWidth())
        self.glasses1transparent2.setSizePolicy(sizePolicy)
        self.glasses1transparent2.setMaximumSize(QtCore.QSize(120, 120))
        self.glasses1transparent2.setAutoFillBackground(False)
        self.glasses1transparent2.setText("")
        self.glasses1transparent2.setPixmap(QtGui.QPixmap("images/ghost90.png"))
        self.glasses1transparent2.setScaledContents(True)
        self.glasses1transparent2.setObjectName("glasses1transparent2")
        self.freqlistl = QtWidgets.QLabel(self.centralwidget)
        self.freqlistl.setGeometry(QtCore.QRect(30, 810, 151, 181))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.freqlistl.setFont(font)
        self.freqlistl.setScaledContents(False)
        self.freqlistl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.freqlistl.setObjectName("freqlistl")
        self.warning_2 = QtWidgets.QLabel(self.centralwidget)
        self.warning_2.setGeometry(QtCore.QRect(27, 400, 711, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_2.sizePolicy().hasHeightForWidth())
        self.warning_2.setSizePolicy(sizePolicy)
        self.warning_2.setMinimumSize(QtCore.QSize(0, 0))
        self.warning_2.setMaximumSize(QtCore.QSize(1000, 500))
        self.warning_2.setText("")
        self.warning_2.setPixmap(QtGui.QPixmap("images/map5.png"))
        self.warning_2.setScaledContents(True)
        self.warning_2.setObjectName("warning_2")
        self.element2_4 = QtWidgets.QLabel(self.centralwidget)
        self.element2_4.setGeometry(QtCore.QRect(10, 19, 731, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_4.sizePolicy().hasHeightForWidth())
        self.element2_4.setSizePolicy(sizePolicy)
        self.element2_4.setAutoFillBackground(False)
        self.element2_4.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_4.setText("")
        self.element2_4.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_4.setScaledContents(True)
        self.element2_4.setObjectName("element2_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(145, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(261, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(379, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(498, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(612, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.zonebred = QtWidgets.QLabel(self.centralwidget)
        self.zonebred.setGeometry(QtCore.QRect(30, 400, 701, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonebred.sizePolicy().hasHeightForWidth())
        self.zonebred.setSizePolicy(sizePolicy)
        self.zonebred.setMinimumSize(QtCore.QSize(0, 0))
        self.zonebred.setMaximumSize(QtCore.QSize(1000, 500))
        self.zonebred.setText("")
        self.zonebred.setPixmap(QtGui.QPixmap("images/zone2red2.png"))
        self.zonebred.setScaledContents(True)
        self.zonebred.setObjectName("zonebred")
        self.zonelred = QtWidgets.QLabel(self.centralwidget)
        self.zonelred.setGeometry(QtCore.QRect(25, 400, 711, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonelred.sizePolicy().hasHeightForWidth())
        self.zonelred.setSizePolicy(sizePolicy)
        self.zonelred.setMinimumSize(QtCore.QSize(0, 0))
        self.zonelred.setMaximumSize(QtCore.QSize(1000, 500))
        self.zonelred.setText("")
        self.zonelred.setPixmap(QtGui.QPixmap("images/zone1red2.png"))
        self.zonelred.setScaledContents(True)
        self.zonelred.setObjectName("zonelred")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(1020, 90, 211, 731))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.lasergrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.lasergrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.lasergrid.setContentsMargins(0, 0, 0, 0)
        self.lasergrid.setObjectName("lasergrid")
        self.element3_4 = QtWidgets.QLabel(self.centralwidget)
        self.element3_4.setGeometry(QtCore.QRect(760, 20, 141, 811))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element3_4.sizePolicy().hasHeightForWidth())
        self.element3_4.setSizePolicy(sizePolicy)
        self.element3_4.setAutoFillBackground(False)
        self.element3_4.setFrameShape(QtWidgets.QFrame.Box)
        self.element3_4.setText("")
        self.element3_4.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element3_4.setScaledContents(True)
        self.element3_4.setObjectName("element3_4")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(770, 90, 121, 731))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.lasernames = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.lasernames.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.lasernames.setContentsMargins(0, 0, 0, 0)
        self.lasernames.setObjectName("lasernames")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(770, 30, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.element3_5 = QtWidgets.QLabel(self.centralwidget)
        self.element3_5.setGeometry(QtCore.QRect(910, 20, 91, 811))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element3_5.sizePolicy().hasHeightForWidth())
        self.element3_5.setSizePolicy(sizePolicy)
        self.element3_5.setAutoFillBackground(False)
        self.element3_5.setFrameShape(QtWidgets.QFrame.Box)
        self.element3_5.setText("")
        self.element3_5.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element3_5.setScaledContents(True)
        self.element3_5.setObjectName("element3_5")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(920, 30, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(920, 90, 71, 731))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.laseronoff = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.laseronoff.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.laseronoff.setContentsMargins(0, 0, 0, 0)
        self.laseronoff.setObjectName("laseronoff")
        self.element2_5 = QtWidgets.QLabel(self.centralwidget)
        self.element2_5.setGeometry(QtCore.QRect(240, 760, 201, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_5.sizePolicy().hasHeightForWidth())
        self.element2_5.setSizePolicy(sizePolicy)
        self.element2_5.setAutoFillBackground(False)
        self.element2_5.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.element2_5.setText("")
        self.element2_5.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_5.setScaledContents(True)
        self.element2_5.setObjectName("element2_5")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(257, 760, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.freqlistb = QtWidgets.QLabel(self.centralwidget)
        self.freqlistb.setGeometry(QtCore.QRect(260, 810, 151, 181))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.freqlistb.setFont(font)
        self.freqlistb.setScaledContents(False)
        self.freqlistb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.freqlistb.setObjectName("freqlistb")
        self.element2_6 = QtWidgets.QLabel(self.centralwidget)
        self.element2_6.setGeometry(QtCore.QRect(760, 840, 481, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_6.sizePolicy().hasHeightForWidth())
        self.element2_6.setSizePolicy(sizePolicy)
        self.element2_6.setAutoFillBackground(False)
        self.element2_6.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.element2_6.setText("")
        self.element2_6.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_6.setScaledContents(True)
        self.element2_6.setObjectName("element2_6")
        self.zoneinfo = QtWidgets.QLabel(self.centralwidget)
        self.zoneinfo.setGeometry(QtCore.QRect(770, 890, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.zoneinfo.setFont(font)
        self.zoneinfo.setScaledContents(False)
        self.zoneinfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.zoneinfo.setObjectName("zoneinfo")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(770, 840, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(180, 460, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(24)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(240, 620, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(24)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 810, 51, 41))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/boxgreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.element2_7 = QtWidgets.QLabel(self.centralwidget)
        self.element2_7.setGeometry(QtCore.QRect(470, 760, 271, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_7.sizePolicy().hasHeightForWidth())
        self.element2_7.setSizePolicy(sizePolicy)
        self.element2_7.setAutoFillBackground(False)
        self.element2_7.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.element2_7.setText("")
        self.element2_7.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_7.setScaledContents(True)
        self.element2_7.setObjectName("element2_7")
        self.freqlistb_2 = QtWidgets.QLabel(self.centralwidget)
        self.freqlistb_2.setGeometry(QtCore.QRect(530, 820, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.freqlistb_2.setFont(font)
        self.freqlistb_2.setScaledContents(False)
        self.freqlistb_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.freqlistb_2.setObjectName("freqlistb_2")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(490, 760, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 890, 51, 41))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/boxred.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 850, 51, 41))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/boxyellow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.freqlistb_3 = QtWidgets.QLabel(self.centralwidget)
        self.freqlistb_3.setGeometry(QtCore.QRect(530, 860, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.freqlistb_3.setFont(font)
        self.freqlistb_3.setScaledContents(False)
        self.freqlistb_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.freqlistb_3.setObjectName("freqlistb_3")
        self.freqlistb_4 = QtWidgets.QLabel(self.centralwidget)
        self.freqlistb_4.setGeometry(QtCore.QRect(530, 900, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.freqlistb_4.setFont(font)
        self.freqlistb_4.setScaledContents(False)
        self.freqlistb_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.freqlistb_4.setObjectName("freqlistb_4")
        self.background.raise_()
        self.element3_2.raise_()
        self.element3_5.raise_()
        self.element2_3.raise_()
        self.element2.raise_()
        self.label_2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.glasses2transparent.raise_()
        self.glasses5transparent.raise_()
        self.glasses1transparent.raise_()
        self.element2_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.glasses3transparent.raise_()
        self.glasses4transparent.raise_()
        self.element3_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.glasses4transparent2.raise_()
        self.glasses2transparent2.raise_()
        self.glasses3transparent2.raise_()
        self.glasses1transparent2.raise_()
        self.glasses5transparent2.raise_()
        self.freqlistl.raise_()
        self.warning_2.raise_()
        self.element2_4.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.zonebred.raise_()
        self.zonelred.raise_()
        self.gridLayoutWidget.raise_()
        self.element3_4.raise_()
        self.gridLayoutWidget_2.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.gridLayoutWidget_3.raise_()
        self.element2_5.raise_()
        self.label_16.raise_()
        self.freqlistb.raise_()
        self.element2_6.raise_()
        self.zoneinfo.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.element2_7.raise_()
        self.pushButton.raise_()
        self.freqlistb_2.raise_()
        self.label_20.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.freqlistb_3.raise_()
        self.freqlistb_4.raise_()
        self.warning.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">LCA 1:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Wavelengths 1</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">Zone State</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">MAP</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">LCA 2:</span></p></body></html>"))
        self.freqlistl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Zone 1</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">None</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG6</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG1</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG7</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG12</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">Glassses:</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">Laser</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">On/Off</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">Wavelengths 2</span></p></body></html>"))
        self.freqlistb.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Zone 1</span></p></body></html>"))
        self.zoneinfo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\"></span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">Zone Info</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "LCA 1"))
        self.label_19.setText(_translate("MainWindow", "LCA 2"))
        self.freqlistb_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Enclosed</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">Legend</span></p></body></html>"))
        self.freqlistb_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Unenclosed and aligned</span></p></body></html>"))
        self.freqlistb_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Unenclosed and unaligned</span></p></body></html>"))
