# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simple.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1364, 1028)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, 0, 1511, 1171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background.sizePolicy().hasHeightForWidth())
        self.background.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.background.setFont(font)
        self.background.setAutoFillBackground(False)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("images/gui1background.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.element2 = QtWidgets.QLabel(self.centralwidget)
        self.element2.setGeometry(QtCore.QRect(49, 438, 601, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2.sizePolicy().hasHeightForWidth())
        self.element2.setSizePolicy(sizePolicy)
        self.element2.setAutoFillBackground(False)
        self.element2.setFrameShape(QtWidgets.QFrame.Box)
        self.element2.setText("")
        self.element2.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2.setScaledContents(True)
        self.element2.setObjectName("element2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(49, 448, 601, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.glasses2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses2.sizePolicy().hasHeightForWidth())
        self.glasses2.setSizePolicy(sizePolicy)
        self.glasses2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses2.setText("")
        self.glasses2.setPixmap(QtGui.QPixmap("images/checkgreen2.png"))
        self.glasses2.setScaledContents(True)
        self.glasses2.setObjectName("glasses2")
        self.horizontalLayout.addWidget(self.glasses2)
        self.glasses3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses3.sizePolicy().hasHeightForWidth())
        self.glasses3.setSizePolicy(sizePolicy)
        self.glasses3.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses3.setText("")
        self.glasses3.setPixmap(QtGui.QPixmap("images/checkgreen2.png"))
        self.glasses3.setScaledContents(True)
        self.glasses3.setObjectName("glasses3")
        self.horizontalLayout.addWidget(self.glasses3)
        self.glasses4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses4.sizePolicy().hasHeightForWidth())
        self.glasses4.setSizePolicy(sizePolicy)
        self.glasses4.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses4.setText("")
        self.glasses4.setPixmap(QtGui.QPixmap("images/checkgreen2.png"))
        self.glasses4.setScaledContents(True)
        self.glasses4.setObjectName("glasses4")
        self.horizontalLayout.addWidget(self.glasses4)
        self.glasses5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses5.sizePolicy().hasHeightForWidth())
        self.glasses5.setSizePolicy(sizePolicy)
        self.glasses5.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses5.setText("")
        self.glasses5.setPixmap(QtGui.QPixmap("images/checkgreen2.png"))
        self.glasses5.setScaledContents(True)
        self.glasses5.setObjectName("glasses5")
        self.horizontalLayout.addWidget(self.glasses5)
        self.element2_2 = QtWidgets.QLabel(self.centralwidget)
        self.element2_2.setGeometry(QtCore.QRect(670, 320, 171, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_2.sizePolicy().hasHeightForWidth())
        self.element2_2.setSizePolicy(sizePolicy)
        self.element2_2.setAutoFillBackground(False)
        self.element2_2.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.element2_2.setText("")
        self.element2_2.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_2.setScaledContents(True)
        self.element2_2.setObjectName("element2_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(680, 320, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(900, 50, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.element3_3 = QtWidgets.QLabel(self.centralwidget)
        self.element3_3.setGeometry(QtCore.QRect(880, 40, 471, 941))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element3_3.sizePolicy().hasHeightForWidth())
        self.element3_3.setSizePolicy(sizePolicy)
        self.element3_3.setAutoFillBackground(False)
        self.element3_3.setFrameShape(QtWidgets.QFrame.Box)
        self.element3_3.setText("")
        self.element3_3.setPixmap(QtGui.QPixmap("images/gui1element6.png"))
        self.element3_3.setScaledContents(True)
        self.element3_3.setObjectName("element3_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 680, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(24)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(49, 816, 601, 102))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.glasses2_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses2_2.sizePolicy().hasHeightForWidth())
        self.glasses2_2.setSizePolicy(sizePolicy)
        self.glasses2_2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses2_2.setText("")
        self.glasses2_2.setPixmap(QtGui.QPixmap("images/checkgreen2.png"))
        self.glasses2_2.setScaledContents(True)
        self.glasses2_2.setObjectName("glasses2_2")
        self.horizontalLayout_2.addWidget(self.glasses2_2)
        self.glasses3_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses3_2.sizePolicy().hasHeightForWidth())
        self.glasses3_2.setSizePolicy(sizePolicy)
        self.glasses3_2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses3_2.setText("")
        self.glasses3_2.setPixmap(QtGui.QPixmap("images/checkgreen2.png"))
        self.glasses3_2.setScaledContents(True)
        self.glasses3_2.setObjectName("glasses3_2")
        self.horizontalLayout_2.addWidget(self.glasses3_2)
        self.glasses4_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses4_2.sizePolicy().hasHeightForWidth())
        self.glasses4_2.setSizePolicy(sizePolicy)
        self.glasses4_2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses4_2.setText("")
        self.glasses4_2.setPixmap(QtGui.QPixmap("images/checkgreen2.png"))
        self.glasses4_2.setScaledContents(True)
        self.glasses4_2.setObjectName("glasses4_2")
        self.horizontalLayout_2.addWidget(self.glasses4_2)
        self.glasses5_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glasses5_2.sizePolicy().hasHeightForWidth())
        self.glasses5_2.setSizePolicy(sizePolicy)
        self.glasses5_2.setMaximumSize(QtCore.QSize(100, 100))
        self.glasses5_2.setText("")
        self.glasses5_2.setPixmap(QtGui.QPixmap("images/checkgreen2.png"))
        self.glasses5_2.setScaledContents(True)
        self.glasses5_2.setObjectName("glasses5_2")
        self.horizontalLayout_2.addWidget(self.glasses5_2)
        self.element2_3 = QtWidgets.QLabel(self.centralwidget)
        self.element2_3.setGeometry(QtCore.QRect(49, 806, 601, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_3.sizePolicy().hasHeightForWidth())
        self.element2_3.setSizePolicy(sizePolicy)
        self.element2_3.setAutoFillBackground(False)
        self.element2_3.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_3.setText("")
        self.element2_3.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_3.setScaledContents(True)
        self.element2_3.setObjectName("element2_3")
        self.freqlistl = QtWidgets.QLabel(self.centralwidget)
        self.freqlistl.setGeometry(QtCore.QRect(690, 370, 131, 201))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.freqlistl.setFont(font)
        self.freqlistl.setScaledContents(False)
        self.freqlistl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.freqlistl.setObjectName("freqlistl")
        self.map = QtWidgets.QLabel(self.centralwidget)
        self.map.setGeometry(QtCore.QRect(880, 90, 491, 871))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map.sizePolicy().hasHeightForWidth())
        self.map.setSizePolicy(sizePolicy)
        self.map.setMinimumSize(QtCore.QSize(0, 0))
        self.map.setMaximumSize(QtCore.QSize(500, 1000))
        self.map.setText("")
        self.map.setPixmap(QtGui.QPixmap("images/map6.png"))
        self.map.setScaledContents(True)
        self.map.setObjectName("map")
        self.element2_4 = QtWidgets.QLabel(self.centralwidget)
        self.element2_4.setGeometry(QtCore.QRect(48, 379, 601, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_4.sizePolicy().hasHeightForWidth())
        self.element2_4.setSizePolicy(sizePolicy)
        self.element2_4.setAutoFillBackground(False)
        self.element2_4.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_4.setText("")
        self.element2_4.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_4.setScaledContents(True)
        self.element2_4.setObjectName("element2_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(79, 380, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(220, 380, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(359, 380, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(500, 380, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.zonebred = QtWidgets.QLabel(self.centralwidget)
        self.zonebred.setGeometry(QtCore.QRect(880, 90, 491, 871))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonebred.sizePolicy().hasHeightForWidth())
        self.zonebred.setSizePolicy(sizePolicy)
        self.zonebred.setMinimumSize(QtCore.QSize(0, 0))
        self.zonebred.setMaximumSize(QtCore.QSize(500, 1000))
        self.zonebred.setText("")
        self.zonebred.setPixmap(QtGui.QPixmap("images/map6red2.png"))
        self.zonebred.setScaledContents(True)
        self.zonebred.setObjectName("zonebred")
        self.zonelred = QtWidgets.QLabel(self.centralwidget)
        self.zonelred.setGeometry(QtCore.QRect(880, 90, 491, 871))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonelred.sizePolicy().hasHeightForWidth())
        self.zonelred.setSizePolicy(sizePolicy)
        self.zonelred.setMinimumSize(QtCore.QSize(0, 0))
        self.zonelred.setMaximumSize(QtCore.QSize(500, 1000))
        self.zonelred.setText("")
        self.zonelred.setPixmap(QtGui.QPixmap("images/map6red1.png"))
        self.zonelred.setScaledContents(True)
        self.zonelred.setObjectName("zonelred")
        self.element2_5 = QtWidgets.QLabel(self.centralwidget)
        self.element2_5.setGeometry(QtCore.QRect(670, 690, 171, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_5.sizePolicy().hasHeightForWidth())
        self.element2_5.setSizePolicy(sizePolicy)
        self.element2_5.setAutoFillBackground(False)
        self.element2_5.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.element2_5.setText("")
        self.element2_5.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_5.setScaledContents(True)
        self.element2_5.setObjectName("element2_5")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(680, 690, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.freqlistb = QtWidgets.QLabel(self.centralwidget)
        self.freqlistb.setGeometry(QtCore.QRect(690, 740, 131, 201))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(12)
        self.freqlistb.setFont(font)
        self.freqlistb.setScaledContents(False)
        self.freqlistb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.freqlistb.setObjectName("freqlistb")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(980, 650, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(24)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1190, 580, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(24)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.element2_6 = QtWidgets.QLabel(self.centralwidget)
        self.element2_6.setGeometry(QtCore.QRect(49, 749, 601, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_6.sizePolicy().hasHeightForWidth())
        self.element2_6.setSizePolicy(sizePolicy)
        self.element2_6.setAutoFillBackground(False)
        self.element2_6.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_6.setText("")
        self.element2_6.setPixmap(QtGui.QPixmap("images/gui1element1.png"))
        self.element2_6.setScaledContents(True)
        self.element2_6.setObjectName("element2_6")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(221, 750, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(501, 750, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(360, 750, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(80, 750, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.element2_7 = QtWidgets.QLabel(self.centralwidget)
        self.element2_7.setGeometry(QtCore.QRect(20, 300, 841, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_7.sizePolicy().hasHeightForWidth())
        self.element2_7.setSizePolicy(sizePolicy)
        self.element2_7.setAutoFillBackground(False)
        self.element2_7.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.element2_7.setText("")
        self.element2_7.setPixmap(QtGui.QPixmap("images/gui1element6.png"))
        self.element2_7.setScaledContents(True)
        self.element2_7.setObjectName("element2_7")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(40, 310, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(24)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.element2_8 = QtWidgets.QLabel(self.centralwidget)
        self.element2_8.setGeometry(QtCore.QRect(20, 670, 841, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.element2_8.sizePolicy().hasHeightForWidth())
        self.element2_8.setSizePolicy(sizePolicy)
        self.element2_8.setAutoFillBackground(False)
        self.element2_8.setFrameShape(QtWidgets.QFrame.Box)
        self.element2_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.element2_8.setText("")
        self.element2_8.setPixmap(QtGui.QPixmap("images/gui1element6.png"))
        self.element2_8.setScaledContents(True)
        self.element2_8.setObjectName("element2_8")
        self.warning = QtWidgets.QLabel(self.centralwidget)
        self.warning.setGeometry(QtCore.QRect(770, 570, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning.sizePolicy().hasHeightForWidth())
        self.warning.setSizePolicy(sizePolicy)
        self.warning.setMinimumSize(QtCore.QSize(500, 500))
        self.warning.setMaximumSize(QtCore.QSize(500, 500))
        self.warning.setText("")
        self.warning.setPixmap(QtGui.QPixmap("images/exclamation.png"))
        self.warning.setScaledContents(True)
        self.warning.setObjectName("warning")
        self.zonelyellow = QtWidgets.QLabel(self.centralwidget)
        self.zonelyellow.setGeometry(QtCore.QRect(880, 90, 491, 871))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonelyellow.sizePolicy().hasHeightForWidth())
        self.zonelyellow.setSizePolicy(sizePolicy)
        self.zonelyellow.setMinimumSize(QtCore.QSize(0, 0))
        self.zonelyellow.setMaximumSize(QtCore.QSize(500, 1000))
        self.zonelyellow.setText("")
        self.zonelyellow.setPixmap(QtGui.QPixmap("images/map6yellow1.png"))
        self.zonelyellow.setScaledContents(True)
        self.zonelyellow.setObjectName("zonelyellow")
        self.zonebyellow = QtWidgets.QLabel(self.centralwidget)
        self.zonebyellow.setGeometry(QtCore.QRect(880, 90, 491, 871))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonebyellow.sizePolicy().hasHeightForWidth())
        self.zonebyellow.setSizePolicy(sizePolicy)
        self.zonebyellow.setMinimumSize(QtCore.QSize(0, 0))
        self.zonebyellow.setMaximumSize(QtCore.QSize(500, 1000))
        self.zonebyellow.setText("")
        self.zonebyellow.setPixmap(QtGui.QPixmap("images/map6yellow.png"))
        self.zonebyellow.setScaledContents(True)
        self.zonebyellow.setObjectName("zonebyellow")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(1197, 620, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setTextFormat(QtCore.Qt.RichText)
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(991, 688, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setTextFormat(QtCore.Qt.RichText)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(970, 470, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(16)
        self.label_25.setFont(font)
        self.label_25.setTextFormat(QtCore.Qt.RichText)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(920, 510, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setTextFormat(QtCore.Qt.RichText)
        self.label_26.setObjectName("label_26")
        self.warning_2 = QtWidgets.QLabel(self.centralwidget)
        self.warning_2.setGeometry(QtCore.QRect(30, 50, 200, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_2.sizePolicy().hasHeightForWidth())
        self.warning_2.setSizePolicy(sizePolicy)
        self.warning_2.setMinimumSize(QtCore.QSize(0, 0))
        self.warning_2.setMaximumSize(QtCore.QSize(500, 500))
        self.warning_2.setText("")
        self.warning_2.setPixmap(QtGui.QPixmap("images/warningsign.png"))
        self.warning_2.setScaledContents(True)
        self.warning_2.setObjectName("warning_2")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(260, 40, 561, 221))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.nohazard1 = QtWidgets.QLabel(self.centralwidget)
        self.nohazard1.setGeometry(QtCore.QRect(260, 470, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.nohazard1.setFont(font)
        self.nohazard1.setAlignment(QtCore.Qt.AlignCenter)
        self.nohazard1.setObjectName("nohazard1")
        self.nohazard2 = QtWidgets.QLabel(self.centralwidget)
        self.nohazard2.setGeometry(QtCore.QRect(260, 840, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK HK")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.nohazard2.setFont(font)
        self.nohazard2.setAlignment(QtCore.Qt.AlignCenter)
        self.nohazard2.setObjectName("nohazard2")
        self.background.raise_()
        self.element2_7.raise_()
        self.element2_8.raise_()
        self.element2_3.raise_()
        self.element2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.element2_2.raise_()
        self.label_4.raise_()
        self.element3_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.freqlistl.raise_()
        self.map.raise_()
        self.element2_4.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.element2_5.raise_()
        self.label_16.raise_()
        self.freqlistb.raise_()
        self.element2_6.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.label_21.raise_()
        self.label_23.raise_()
        self.zonelyellow.raise_()
        self.zonebyellow.raise_()
        self.zonelred.raise_()
        self.zonebred.raise_()
        self.label_19.raise_()
        self.warning.raise_()
        self.label_18.raise_()
        self.label_22.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.warning_2.raise_()
        self.label_27.raise_()
        self.nohazard1.raise_()
        self.nohazard2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Lasers On Now</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">MAP</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Laser Containment Area 2</span></p></body></html>"))
        self.freqlistl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Zone 1</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG6</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG1</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG7</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG12</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Lasers On Now</span></p></body></html>"))
        self.freqlistb.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Zone 1</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p>LCA 1</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>LCA 2</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG1</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG12</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG7</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#b0b7c1;\">LG6</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">Laser Containment Area 1</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p>Britton</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p>Linke</p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p>Safe Zone</p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p>B0223 Entrance</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">DANGER</span></p></body></html>"))
        self.nohazard1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">No Hazard</span></p></body></html>"))
        self.nohazard2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#b0b7c1;\">No Hazard</span></p></body></html>"))
